### ISSUE TITLE
Controller doesn't provide full TLS chain

### ISSUE THREAD

**Issue by guillaumefenollar** [mcluseau/kingress#2]
Hello,

Kingress currently seems to only provide leaf certificate, without the full chain (when it's provided in the TLS secret). Thus requests don't work when the local SSL library doesn't know about an intermediate certificate.

Is there a way for kingress to provide full chain as specified in the secret instead ?

**Comment by mcluseau** [comment]
If I remember correctly that was a configuration error so I'm closing this.
